#!/bin/bash -l
#
# version/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

@import Files

declare ipa_path
declare -i need_download=1
declare apple_id
declare apple_id_password
declare apple_id_in_itunesconnect
declare reserved_result=1

declare code
for param in "$@"
do
    if [[ "$param" == "-download" ]]; then
        need_download=0
    elif [[ "$param" == "-reserved" ]]; then
        reserved_result=0
    elif [[ "$param" =~ ^- ]]; then
            code="$param"
    else
        if [[ "$code" == "-ipa" ]]; then
            ipa_path="$param"
        elif [[ "$code" == "-apple_id" ]]; then
            apple_id="$param"
        elif [[ "$code" == "-password" ]]; then
            apple_id_password="$param"
        elif [[ "$code" == "-app_id" ]]; then
            apple_id_in_itunesconnect="$param"
        fi
    fi
done


if [[ -z $ipa_path ]]; then 
    print -c "red" "Ipa path is required. please pass the path by -ipa."
    exit 1
fi

if [[ -z $apple_id ]]; then
    apple_id="$APPLE_ID"
fi

if [[ -z $apple_id_password ]]; then
    apple_id_password="$APPLE_ID_PASSWORD"
fi

declare IPA_FILENAME=$(basename "$ipa_path")
declare LOCAL_IPA_PATh="$ipa_path"
declare IPA_BELONG_FOLDER=$(dirname "$ipa_path")

if [[ -n $ipa_path && $need_download == 0 ]]; then
    IPA_BELONG_FOLDER="."
    LOCAL_IPA_PATh="$IPA_BELONG_FOLDER/$IPA_FILENAME"
    curl -o "$LOCAL_IPA_PATh" "$ipa_path" #ipa_path:url
fi

declare MD5=$(md5 -q "$LOCAL_IPA_PATh")
declare BYTESIZE=$(stat -f "%z" "$LOCAL_IPA_PATh")

declare ITMSP_BUNDLE_NAME="${IPA_FILENAME}.itmsp"
declare ITMSP_DIR="$IPA_BELONG_FOLDER/itmsp_${IPA_FILENAME}"

#如果之前的存在，就移除。
delete "${ITMSP_DIR}"

mkdir "${ITMSP_DIR}"
mkdir "${ITMSP_DIR}/$ITMSP_BUNDLE_NAME"

cp "${LOCAL_IPA_PATh}" "$ITMSP_DIR/$ITMSP_BUNDLE_NAME"
delete "$LOCAL_IPA_PATh"

cat <<EOM > "${ITMSP_DIR}/${ITMSP_BUNDLE_NAME}/metadata.xml"
<?xml version="1.0" encoding="UTF-8"?>
<package version="software4.7" xmlns="http://apple.com/itunes/importer">
<software_assets apple_id="$apple_id_in_itunesconnect">
    <asset type="bundle">
        <data_file>
            <file_name>$IPA_FILENAME</file_name>
            <checksum type="md5">$MD5</checksum>
            <size>$BYTESIZE</size>
        </data_file>
    </asset>
</software_assets>
</package>
EOM

/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter -m upload -f "${ITMSP_DIR}" -u "$apple_id" -p "$apple_id_password" -v detailed

if [[ $? == 0 ]]; then 
    if [[ $reserved_result == false ]]; then
        delete "${ITMSP_DIR}"
    fi
    return 0
else 
    return 1
fi