#!/bin/bash
#
# modules/init
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f @import

function @import() {
  declare module="$1"
  declare module_path="$MODULES_DIR/$module"

  if [[ "$module" == "" ]]; then
    print -c "red" -s bold "-- Module name can't be empty! ----------"
    return 1
  fi

  if [[ -e "$module_path" ]]; then
    pushd "$module_path" >> /dev/null
    source @.imports >> /dev/null
    popd >> /dev/null
    print -c cyan -s bold ">> Module [$module] import succeed."
  else
    print -c "red" -s bold "-- Module [$module] not found! ----------"
  fi
}
