#!/bin/bash -l
#
# matcha
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

#從執行 shell 路徑判定builder路徑


if [[ -z "$MATCHA_BUILDER_BASE" ]]; then
  declare EXEC_PATH="$BASH_SOURCE"
  declare EXEC_DIR=$(dirname "$EXEC_PATH")
  pushd "$EXEC_DIR" >> /dev/null

  export MATCHA_BUILDER_BASE=$(pwd)
else
  pushd "$MATCHA_BUILDER_BASE" >> /dev/null
fi

declare -a array=($@)
if [[ "${array[@]}" =~ "basic" ]]; then
  source .basic $@
elif [[ "${array[@]}" =~ "build" ]]; then
  source .build $@
fi

popd >> /dev/null
