#!/bin/bash -l
#
# matcha
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#


#從執行 shell 路徑判定builder路徑
declare EXEC_PATH

EXEC_PATH="$BASH_SOURCE" && [[ -L "$BASH_SOURCE" ]] && EXEC_PATH=$(readlink "$BASH_SOURCE");

declare EXEC_DIR=$(dirname "$EXEC_PATH")

cd "$EXEC_DIR" >/dev/null 2>&1
MATCHA_BUILDER_BASE=$(pwd)
cd - >/dev/null 2>&1

source "$MATCHA_BUILDER_BASE/.prefix" >/dev/null 2>&1
MODULES_FOLDER="$MATCHA_BUILDER_BASE/modules"

@import Prints --silent

function matcha() {
  declare -a array=($@)

  BUILD_CI=1 && [[ "${array[@]}" =~ "-ci" ]] && BUILD_CI=0;
  DEBUG_MODE=1 && [[ "${array[@]}" =~ "-debug" ]] && DEBUG_MODE=0;

  [[ -n $1 && "$1" != *"-"*  ]] && @exec "$@" && return 0;
  [[ "$0" == *"bash"* ]] && welcome \
  && [[ $BUILD_CI == 1 ]] && tips && return 0;

}

#相容舊版
if [[ "$0" == *"bash" && -L "$BASH_SOURCE" ]]; then
  matcha "$@"
fi
