#!/bin/bash
#
# archive/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

welcome

@import Prints
@import Files

source .envs
source .prefix "$@"

if [[ "${array[@]}" =~ "-ndp" ]]; then
  NEED_DOWNLOAD_PROVISION_PROFILE=1
fi

#=====Common imports=====
@import Builder

setup_delegate "$@"

if [[ -e "$APP_PATH" ]]; then
  switch_dir_to "$APP_PATH"
  if [[ -e "$DELEGATE_FILE_NAME" && "$SOURCE_TYPE" == "path" && "$APP_PATH" != "" && "$DELEGATE" == "" ]]; then
    DELEGATE="$APP_PATH/$DELEGATE_FILE_NAME"
  fi
  restore_dir
fi

read_delegate "$DELEGATE"

will_launch "$@"

clean tmp

validate_env_variables

keychain unlock $PASSWD

did_launch

will_exec "builder"
exec_script _init

if [[ "$SOURCE_TYPE" == "git" ]]; then
  exec_script clone_app
fi

phase_print "Configuring path..."

config_env_variables
mkdirs "log" "export"
mkdirFolder "$TMP_PATH"

declare -i configurations_count=${#BUILD_CONFIGURATIONS[@]}
if [[ $configurations_count == 0 ]]; then
  switch_dir_to "$APP_PATH"
  BUILD_CONFIGURATIONS=($(xcodebuild -showBuildSettings | grep 'CONFIGURATION =' | sed 's/    CONFIGURATION = //g'))
  restore_dir
fi

for (( i=0; i<${configurations_count}; i++ ));
do
  switch_dir_to "$APP_PATH"

	BUILD_CONFIGURATION=${BUILD_CONFIGURATIONS[$i]}
	print -c green "using configuration: $BUILD_CONFIGURATION"

	if [[ $BUILD_CI != 0 ]]; then
		EXPORT_FOLDER="$EXPORT_FOLDER/${BUILD_CONFIGURATION}_${BUILD_DATETIME}"
	fi

  #===== variables from xcode projects
  xc_setup_variables
  #=============================
	ARCHIVE_NAME="${PROJ_NAME}_${BUILD_CONFIGURATION}"
	EXPORT_SUB_FOLDER="${BUILD_CONFIGURATION}_${BUILD_DATETIME}"

  exec_script setup_codesign
  exec_script archive_app
	exec_script export_ipa

	APP_ID=""
	UUID=""

  restore_dir
done

did_exec "builder"

did_end
