#!/bin/bash
#
# Prints/print_color
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f pc
declare -f pcs

function pc() {

  declare result_str=""
  result_str=$(get_format_string "$@")
  reset_format=$(get_format "reset_all" "" "")

  if [[ $BUILD_CI == 0 ]]; then
    echo "$result_str"
  else
    echo -e "$result_str$reset_format"
  fi

}

function pcs() {

  declare result_str=""

  for var in "$@"
  do
     formated_string=$(get_format_string $var)
     result_str="${result_str}${formated_string}"
  done

  reset_format=$(get_format "reset_all" "" "")

  if [[ $BUILD_CI == 0 ]]; then
    echo $result_str
  else
    echo -e "$result_str$reset_format"
  fi
}

