#!/bin/bash
#
# update/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

if [[ "$2" == "list" ]]; then
  ls "$MATCHA_BUILDER_BASE/command"
fi
