#!/bin/bash
#
# import/source
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare module=$(basename "$2")

declare -i SILENT_IMPORT=1
if [[ "$@" == *"--silent"* ]]; then
  SILENT_IMPORT=0
fi


[[ "$module" == "" && $SILENT_IMPORT == 1 ]] && @error "-- Module name can't be empty! ----------" && return 1;

declare module_dir=$(dirname "$2")
declare module_path="$module_dir/$module"
if [[ ! -e "$module_path/@.imports" ]]; then
  module_path="$MODULES_FOLDER/$module"
fi

if [[ -L "$module_path.mm" ]]; then
  real=$(readlink "$module_path.mm")
  module_path=$(dirname "$real")
fi

if [[ -e "$module_path" ]]; then
  pushd "$module_path" >/dev/null 2>&1
  source @.imports >/dev/null 2>&1
  popd >/dev/null 2>&1
  [[ $SILENT_IMPORT == 1 ]] && @log ">> Module [$module] import succeed." && return 0;
else
  [[ $SILENT_IMPORT == 1 ]] && @error "-- Module [$module] not found! ----------" && return 1;
fi
