#!/bin/bash
#
# files
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f clean
declare -f delete
declare -f open_finder

function clean() {

  declare parameters="$@"
  if [[ "${parameters[@]}" =~ "-need_ci" && $BUILD_CI != 0  ]]; then
    return
  fi

  for cmd in $parameters
  do
    if [[ "$cmd" =~ ^-  ]]; then
      continue
    fi

    lower="$(echo $cmd | tr '[:upper:]' '[:lower:]')"
    phase_print "cleanning $lower files"
    if [[ "$cmd" == "built" ]]; then
      delete "${BUILD_PATH}"
      print -c "green" "deleted built path: ${BUILD_PATH}..."
    elif [[ "$cmd" == "tmp" ]]; then
      delete "${TMP_PATH}"
      print -c "green" "deleted tmp path: ${TMP_PATH}..."
    elif [[ "$cmd" == "provision_profile" ]]; then
      delete "$PROVISIONING_FOLDER/$PROVISIONING_PROFILE"
      if [ "${APPLE_ID_PASSWORD}" != "" ]; then
            fastlane-credentials remove --username "${APPLE_ID}"
      fi
      print -c "green" "deleted profile path: $PROVISIONING_FOLDER/$PROVISIONING_PROFILE..."
    elif [[ "$cmd" == "exports" ]]; then
      delete "$EXPORT_FOLDER"
      print -c "green" "deleted export path: $EXPORT_FOLDER..."
    fi
  done
}

function delete(){
  path="$1"
  rm -rf "$path"
}

function mkdirFolder() {

  for mf in "$@"
  do
    if [ ! -d "$mf" ]; then
      mkdir -p "$mf"
    fi
  done

}

function mkdirs(){
  for dir in "$@"
  do
    if [[ "$dir" == "log" && $BUILD_CI != 0 ]]; then
      mkdirFolder "$LOG_FOLDER"
    fi

    if [[ "$dir" == "export" ]]; then
      mkdirFolder "$EXPORT_FOLDER"
    fi

  done
}

function open_finder() {

  if [[ $BUILD_CI == 0 ]]; then
    return
  fi

  path="$1"
  if [[ "$1" == "export" ]]; then
    path="$EXPORT_FOLDER"
  fi
  open "$path"
}
