#!/bin/bash
#
# subscript
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f exec_script
declare -f exec_scripts

function exec_script () {
  script_name=$1
  parameter=$2

  source "${SUBSCRIPT_DIR}/${script_name}.sh" "$parameter"
}

function exec_scripts () {

  for name in $@
  do
      exec_script "$name"
  done
}
