#!/bin/bash
#
# call_delegate
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f will_launch
declare -f did_launch
declare -f will_exec
declare -f did_exec
declare -f did_end
declare -f did_terminate

function will_launch() {
  if [[ $(@exists -f builder_will_launch) == 0 ]]; then
    dir_path=$(dirname "$DELEGATE")
    switch_dir_to "$dir_path"
    builder_will_launch $@
    restore_dir
  fi
}

function did_launch() {
  if [[ $(@exists -f builder_did_launch) == 0 ]]; then
    dir_path=$(dirname "$DELEGATE")
    switch_dir_to "$dir_path"
    builder_did_launch $@
    restore_dir
  fi
}

function will_exec() {
  if [[ $(@exists -f builder_will_exec) == 0 ]]; then
    dir_path=$(dirname "$DELEGATE")
    switch_dir_to "$dir_path"
    builder_will_exec $@
    restore_dir
  fi
}

function did_exec() {
  if [[ $(@exists -f builder_did_exec) == 0 ]]; then
    dir_path=$(dirname "$DELEGATE")
    switch_dir_to "$dir_path"
    builder_did_exec $@
    restore_dir
  fi
}

function did_end() {
  if [[ $(@exists -f builder_did_end) == 0 ]]; then
    dir_path=$(dirname "$DELEGATE")
    switch_dir_to "$dir_path"
    builder_did_end $@
    restore_dir
  fi
}

function did_terminate(){
  if [[ $(@exists -f builder_did_terminate) == 0 ]]; then
    dir_path=$(dirname "$DELEGATE")
    switch_dir_to "$dir_path"
    builder_did_terminate $@
    restore_dir
  fi
}
