#!/bin/bash
#
# setup
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f setup_delegate
declare -f check_delegate

function setup_delegate(){

  declare code
  for param in "$@"
  do
    if [[ "$param" =~ ^- ]]; then
			code="$param"
		else
      if [[ "$code" == "-project"  ]]; then
        PROJECT_FOLDER_NAME="$param"
        DELEGATE="$MATCHA_BUILDER_BASE/projects/$PROJECT_FOLDER_NAME/delegate"
        code=""
      elif [[ "$code" == "-delegate"  ]]; then
        DELEGATE="$param"
        code=""
      fi
    fi
  done

  if [[ "$DELEGATE_FILE_NAME" == "" ]]; then
    DELEGATE_FILE_NAME="delegate"
  fi

}

function read_delegate(){
  declare delegate=$(basename "$1")
  declare delegate_dir=$(dirname "$1")
  declare delegate_dir_name=$(basename "$delegate_dir")

  if [[ "$delegate" == "" ]]; then
    ＠print -c yellow -s bold ':Warnning: [DELEGATE] is not setting. Please check it by pass -delegate in the command line.'
  else
    switch_dir_to "$delegate_dir"
    source "$delegate"
    restore_dir
    ＠print -c "green" "using delegate: $delegate_dir_name/$delegate"
  fi
}
