#!/bin/bash
#
# update/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

@import Git --silent
@import Matcha

declare branch="master"
declare code
for param in "$@"
do
    if [[ "$param" =~ ^- ]]; then
            code="$param"
        else
            if [[ "$code" == "-branch" ]]; then
                branch="$param"
            elif [[ "$code" == "-b" ]]; then
                branch=($param)
            fi
        fi
done

declare TAG="1.0"
declare UPDATE_PATH="$HOME/.matcha_update"
mkdirFolder "$UPDATE_PATH"

@log "Cloning Matcha from [$branch]..."
clone -r "https://github.com/gradyzhuo/Matcha.git" -b $branch -t "$UPDATE_PATH" >/dev/null 2>&1

if [[ $? != 0 ]]; then
  @print -c red -s bold "Matcha cloning failed."
  exit $?
fi

cd "$UPDATE_PATH" >> /dev/null
./install.sh
cd - >> /dev/null

delete "$UPDATE_PATH"

if [[ $? == true ]]; then
  @log 'Update succeed.'
fi
