#!/bin/bash
#
# update/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

@import Git

declare TAG="1.0"
declare UPDATE_PATH="$HOME/.matcha_update"
mkdirFolder "$UPDATE_PATH"

@log 'Cloning Matcha...'
clone -r "https://github.com/gradyzhuo/Matcha.git" -b "master" -t "$UPDATE_PATH"

cd "$UPDATE_PATH" >> /dev/null
./install.sh
cd - >> /dev/null

delete "$UPDATE_PATH"

if [[ $? == true ]]; then
  @log 'Update succeed.'
fi
