#!/bin/bash
#
# MailSupport/send_mail
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f send_mail

function send_mail() {

  declare fromuser
  declare touser
  declare subject
  declare content
  declare footer
  declare charset
  declare ccuser
  declare bccuser
  declare replyto
  declare ctype
  declare mime_version="1.1"

  for param in "$@"
  do
    if [[ "$param" =~ ^- ]]; then
      code="$param"
    else
      if [[ "$code" == "-from" ]]; then
        fromuser="$param"
      elif [[ "$code" == "-to" ]]; then
        touser="$param"
      elif [[ "$code" == "-subject" ]]; then
        subject="$param"
      elif [[ "$code" == "-content" ]]; then
        content="$param"
      elif [[ "$code" == "-footer" ]]; then
        footer="$param"
      elif [[ "$code" == "-charset" ]]; then
        charset="$param"
      elif [[ "$code" == "-cc" ]]; then
        ccuser="$param"
      elif [[ "$code" == "-bcc" ]]; then
        bccuser="$param"
      elif [[ "$code" == "-reply_to" ]]; then
        replyto="$param"
      elif [[ "$code" == "-ctype" ]]; then
        ctype="$param"
      fi
    fi
  done

  if [[ "$charset" == "" ]]; then
    charset="UTF-8"
  fi
  if [[ "$ctype" == "" ]]; then
    ctype="text/html"
  fi

  if [[ "$ctype" == "text/html" ]]; then
    if [[ $(@exists -c pandoc) == 0 ]]; then
      content=$(echo "$content" | pandoc -f markdown_github)
    else
      content=$(echo "$content" | sed 's/^/<div>/g'  | sed 's/$/<\/div>/g' | sed 's/<div><\/div>/<br \/>/g')
    fi
  fi

  {
  echo "Mime-Version: $mime_version";
  echo "Content-type:$ctype ; charset=\"$charset\"";
  echo "From: $fromuser";
  echo "Reply-To: : $replyto";
  echo "To: $touser";
  echo "CC: $ccuser";
  echo "Bcc: $bccuser";
  echo "Subject: $subject";

  echo "$content"

  echo "$footer"
  } | sendmail -t
}
