#!/bin/bash
#
# MailSupport/utils
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f plain2html

function plain2html(){
  content="$1"
  if [[ $(@exists -c pandoc) == 0 ]]; then
    content=$(echo "$content" | pandoc -f markdown_github)
  else
    content=$(echo "$content" | sed 's/^/<div>/g'  | sed 's/$/<\/div>/g' | sed 's/<div><\/div>/<br \/>/g')
  fi

  echo "$content"
}



function draft_path() {
  if [[ -n "$1" ]]; then
    declare UUID="$1"
  else
    declare UUID="$CURRENT_MAIL_UUID"
  fi
  echo "$DRAFTS_PATH/$UUID"
}

function draft_parameters_path() {
  DRAFT_FOLDER=$(draft_path "$1")
  echo "$DRAFT_FOLDER/parameters.draft"
}

function draft_header_path() {
  DRAFT_FOLDER=$(draft_path "$1")
  echo "$DRAFT_FOLDER/header.draft"
}

function draft_body_path() {
  DRAFT_FOLDER=$(draft_path "$1")
  echo "$DRAFT_FOLDER/body.draft"
}


function draft_footer_path() {
  DRAFT_FOLDER=$(draft_path "$1")
  echo "$DRAFT_FOLDER/footer.draft"
}
