#!/bin/bash
#
# basic/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

source "$COMMAND_BASE/.prefix" >> /dev/null

MODULES_FOLDER="modules"
MODULES_DIR="$MATCHA_BUILDER_BASE/$MODULES_FOLDER"
source "$MODULES_DIR/main" >> /dev/null

welcome

@import Prints
@import Files
@import BashSupport
