#!/bin/bash
#
# XC/setup
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -x XC_INFO_PLIST_PATH
declare -f xc_show

function xc_show() {
  command="$1"

  declare scheme=""
  declare configuration=""
  declare settings=""

  declare code
  for param in "$@"
  do
    if [[ "$param" =~ ^- ]]; then
			code="$param"
		else
      if [[ "$code" == "-s" ]]; then
        scheme="$param"
      elif [[ "$code" == "-conf" ]]; then
        configuration=($param)
      elif [[ "$code" == "-settings" ]]; then
        settings="$param"
      fi
		fi
  done

  if [[ "build_settings app_id info_plist configuration team specifier_provision_profile" == *"$command"* && -z "$settings" ]]; then
    declare build_settings_cmd="xcodebuild -showBuildSettings"
    if [[ "$scheme" != "" ]]; then
      build_settings_cmd="$build_settings_cmd -scheme $scheme"
    fi
    if [[ "$configuration" != "" ]]; then
      build_settings_cmd="$build_settings_cmd -configuration \"$configuration\""
    fi
    settings=$(eval "$build_settings_cmd")
  fi

  if [[ "$command" == "build_settings" ]]; then
    echo "$settings"
  elif [[ "$command" == "specifier_provision_profile" ]]; then
    echo $(echo "$settings" | grep 'PROVISIONING_PROFILE_SPECIFIER' | sed 's/    PROVISIONING_PROFILE_SPECIFIER = //g')
  elif [[ "$command" == "codesign_style" ]]; then
    echo $(echo "$settings" | grep 'CODE_SIGN_STYLE' | sed 's/    CODE_SIGN_STYLE = //g')
  elif [[ "$command" == "app_id" ]]; then
    echo $(echo "$settings" | grep 'PRODUCT_BUNDLE_IDENTIFIER' | sed 's/    PRODUCT_BUNDLE_IDENTIFIER = //g')
  elif [[ "$command" == "info_plist" ]]; then
    XC_INFO_PLIST_PATH=$(echo "$settings" | grep 'INFOPLIST_FILE' | sed 's/    INFOPLIST_FILE = //g')
    echo "$XC_INFO_PLIST_PATH"
  elif [[ "$command" == "configuration" ]]; then
    echo $(echo "$settings" | grep 'CONFIGURATION =' | sed 's/    CONFIGURATION = //g')
  elif [[ "$command" == "team" ]]; then
    echo $(echo "$settings" | grep 'DEVELOPMENT_TEAM' | sed 's/    DEVELOPMENT_TEAM = //g')
  elif [[ "$command" == "version" ]]; then
    echo $(agvtool mvers -terse1)
  elif [[ "$command" == "build_version" ]]; then
    agv=$(agvtool vers -terse)
    if [[ -n $agv ]]; then
      echo "$agv"
    else
      echo  $(defaults read "$(pwd)/$(xc_show info_plist)"  CFBundleVersion)
    fi
  fi

}
