#!/bin/bash
#
# XC/setup
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f xc_show

function xc_show() {
  command="$1"

  declare scheme=""
  declare configuration=""

  declare code
  for param in "$@"
  do
    if [[ "$param" =~ ^- ]]; then
			code="$param"
		else
      if [[ "$code" == "-s" ]]; then
        scheme="$param"
      elif [[ "$code" == "-conf" ]]; then
        configuration=($param)
      fi
		fi
  done

  build_settings_cmd="xcodebuild -showBuildSettings"
  if [[ "$scheme" != "" ]]; then
    build_settings_cmd="$build_settings_cmd -scheme $scheme"
  fi
  if [[ "$configuration" != "" ]]; then
    build_settings_cmd="$build_settings_cmd -configuration \"$configuration\""
  fi
  # cmd="$cmd -sdk iphoneos"
  # cmd="$cmd -xcconfig \"$codesign_xcconfig\""

  if [[ "$command" == "app_id" ]]; then
    echo $(eval "$build_settings_cmd" | grep 'PRODUCT_BUNDLE_IDENTIFIER' | sed 's/    PRODUCT_BUNDLE_IDENTIFIER = //g')
  elif [[ "$command" == "info_plist" ]]; then
    echo $(eval "$cmd" | grep 'INFOPLIST_FILE' | sed 's/    INFOPLIST_FILE = //g')
  elif [[ "$command" == "default_conf" ]]; then
    echo $(eval "$cmd" | grep 'CONFIGURATION =' | sed 's/    CONFIGURATION = //g')
  elif [[ "$command" == "team" ]]; then
    echo $(eval "$cmd" | grep 'DEVELOPMENT_TEAM' | sed 's/    DEVELOPMENT_TEAM = //g')
  fi
}
