#!/bin/bash
#
# XC/setup
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f xc_setup_variables

function xc_setup_variables {
  cmd="xcodebuild -showBuildSettings"

  cmd="$cmd -scheme $PROJ_SCHEME"
  if [[ "$BUILD_CONFIGURATION" != "" ]]; then
    cmd="$cmd -configuration \"$BUILD_CONFIGURATION\""
  fi

  # cmd="$cmd -sdk iphoneos"
  # cmd="$cmd -xcconfig \"$codesign_xcconfig\""

  #fetch APP_ID
  if [[ "$APP_ID" == "" ]]; then
  	APP_ID=$(eval "$cmd" | grep 'PRODUCT_BUNDLE_IDENTIFIER' | sed 's/    PRODUCT_BUNDLE_IDENTIFIER = //g')
  fi

  #fetch INFO_PLIST
  if [[ "$INFO_PLIST" == "" ]]; then
    INFO_PLIST=$(eval "$cmd" | grep 'INFOPLIST_FILE' | sed 's/    INFOPLIST_FILE = //g')
  fi

  if [[ "$BUILD_CONFIGURATIONS" == "" ]]; then
    BUILD_CONFIGURATIONS=($(eval "$cmd" | grep 'CONFIGURATION =' | sed 's/    CONFIGURATION = //g'))
  fi

  CURRENT_PROJECT_VERSION=$(defaults read "$APP_PATH/$INFO_PLIST"  CFBundleShortVersionString)
  CURRENT_PROJECT_BUILD_VERSION=$(defaults read "$APP_PATH/$INFO_PLIST"  CFBundleVersion)

  DEVELOPMENT_TEAM=$(eval "$cmd" | grep 'DEVELOPMENT_TEAM' | sed 's/    DEVELOPMENT_TEAM = //g')
  if [[ "$DEVELOPMENT_TEAM" != "" ]]; then
    AUTOMATICALLY_MANAGE_SIGIN=0
  else
    AUTOMATICALLY_MANAGE_SIGIN=1
  fi
}
