#!/bin/bash
#
# version/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

print -c red "please use the subcommand as below:"
ls "$MATCHA_BUILDER_BASE/command/uploader"