#!/bin/bash
#
# BashSupport/session
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f shell_session_update #fix, and avoid the error message: 'shell_session_update: command not found'

function shell_session_update() {
  if [[ $? != 0 ]]; then
    did_terminate
    print -c "red" -s bold "Builder is terminated!"
  fi
}
