#!/bin/bash -l
#
# Git/clone
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f clone

function clone() {

declare code
declare respo
declare branch
declare target
declare tag

	for ctx in "$@"
  do
		if [[ "$ctx" =~ ^- ]]; then
			code="$ctx"
		else
			if [[ "$code" == "-r" ]]; then
				respo="$ctx"
			elif [[ "$code" == "-b" ]]; then
				branch="$ctx --single-branch"
			elif [[ "$code" == "-t" ]]; then
				target="$ctx"
			elif [[ "$code" == "-tag" ]]; then
				tag=$"$ctx"
			fi
		fi

		if [[ "$branch" == "" ]]; then
			branch="master"
		fi

		if [[ "$target" == "" ]]; then
			target="."
		fi
  done

	@log -c blue -s bold "$respo cloning..."

	mkdirFolder "${target}"
	git clone -b ${branch} ${respo} "${target}"

  if [[ $? == 0 ]]; then
    @log "$respo cloned..."
  else
    @log "$respo failed..."
  fi

	switch_dir_to "${target}"
	@log "Git tags:\n \"$(git tag -l)\""

	if [[ "$tag" != "" && `git tag -l $tag` == $tag ]]; then
		@log "Checkout tag: $tag..."
		git checkout tags/$tag
		if [[ $? == 0 ]]; then
			@log "Checkout tag/$tag succeed."
		else
			@log "Checkout tag/$tag failed."
		fi

	fi
	restore_dir

}
