#!/bin/bash
#
# Git/clone
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

declare -f clone

function clone() {

declare code
declare respo
declare branch
declare target
declare tag

	for ctx in "$@"
  do
		if [[ "$ctx" =~ ^- ]]; then
			code="$ctx"
		else
			if [[ "$code" == "-r" ]]; then
				respo="$ctx"
			elif [[ "$code" == "-b" ]]; then
				branch="$ctx --single-branch"
			elif [[ "$code" == "-t" ]]; then
				target="$ctx"
			elif [[ "$code" == "-tag" ]]; then
				tag=$"$ctx"
			fi
		fi

		if [[ "$branch" == "" ]]; then
			branch="master"
		fi

		if [[ "$target" == "" ]]; then
			target="."
		fi
  done

	print -c blue -s bold "$respo cloning..."

	mkdirFolder "${target}"
	git clone -b ${branch} ${respo} "${target}"

	switch_dir_to "${target}"
	if [[ "$tag" != "" && `git tag -l $tag` == $tag ]]; then
		@log "Checkout tag: $tag..."
		git checkout tags/$tag
		@log "Checkout succeed."
	fi
	restore_dir

  if [[ $? == 0 ]]; then
    print -c blue -s bold "$respo cloned..."
  else
    print -c red -s bold "$respo failed..."
  fi


}
