#!/bin/bash
#
# print/main
#
# Matcha 1.0, Created by gradyzhuo, enoch_lee.
# Copyright © 2017, Matcha Inc. All rights reserved.
#

@import Prints --silent

a=$(echo "$@" | sed 's/print //g')
pcs "$a"